### ISSUE TITLE
Respond to peer reviews for "Periodicity" paper

### ISSUE THREAD

**Issue by devoworm** [devoworm/Group-Meetings#79]

**Comment by jesparent** [comment]
I will try to be looking at this tonight and /or tomorrow

**Comment by jesparent** [comment]
This is still in review, right ? @devoworm

**Comment by devoworm** [comment]
Yes.

**Comment by jesparent** [comment]
https://www.sciencedirect.com/science/article/abs/pii/S0303264721000629 !

Final "official" biosystems paper here. Nice job team!
